import type { Service } from '../shared/types.ts';
const bitrix='https://www.bitrix24.kz/?utm_source=google&utm_medium=cpc&utm_campaign=kz_Search-B24_brand&utm_content=677467276765-20677362649-157540781249&utm_term=bitrix24&gad_source=1&gad_campaignid=20677362649&gclid=Cj0KCQjw5P7UBhDaARIsAOSlS1NjmDzv0DRsY2BpEYmQw2SchNwsodt2yXS59ic82DSXS0SoG-7D_04aAp7REALw_wcB';
export const services:Service[] = [
 {id:'S01',name:'Электронный документооборот с Российской Федерацией',provider:'idocs',description:'Электронный обмен документами и организация согласований в одном пространстве.',benefits:['Создание и подписание документов','Автоматизация документооборота'],terms:'Состав решения для обмена с РФ и стоимость уточняются у поставщика.',offer:'Меньше бумаги. Больше времени на бизнес.',imageUrl:'/images/documents.png',imageAlt:'Объёмные документы со стрелкой обмена',connectUrl:'https://idocs.kz/#products',displayOrder:1,actionType:'external',sourceUrl:'https://idocs.kz/'},
 {id:'S02',name:'Юрист 24',provider:'Европейская Юридическая Служба',description:'Дистанционная юридическая поддержка для вопросов вашего бизнеса.',benefits:['Консультации онлайн','Помощь по правовым вопросам'],terms:'Тариф, применимая юрисдикция и объём консультаций уточняются у поставщика.',offer:'Юридическая помощь рядом, когда она нужна.',imageUrl:'/images/legal.png',imageAlt:'Объёмные весы и юридический документ',connectUrl:'https://els24.com',displayOrder:2,actionType:'external',sourceUrl:'https://els24.com/'},
 {id:'S03',name:'Поиск поставщиков из Российской Федерации',provider:'ТПП Российской Федерации',description:'Информация для развития деловых связей и поиска партнёров в России.',benefits:['Информация делового сообщества','Возможности для новых связей'],terms:'Формат содействия и условия работы уточняются в ТПП РФ.',offer:'Новые связи для развития вашего бизнеса.',imageUrl:'/images/suppliers.png',imageAlt:'Объёмные коробки и увеличительная линза',connectUrl:'https://tpprf.ru/ru/',displayOrder:3,actionType:'external',sourceUrl:'https://tpprf.ru/ru/'},
 {id:'S04',name:'CRM для вашего бизнеса',provider:'Битрикс24',description:'Клиенты, сделки и задачи команды в одной системе.',benefits:['Работа с клиентами в CRM','Задачи и автоматизация процессов'],terms:'Возможности и стоимость зависят от тарифа Битрикс24.',offer:'Сохраняйте фокус на клиентах и продажах.',imageUrl:'/images/crm.png',imageAlt:'Объёмные связанные карточки клиентов',connectUrl:bitrix,displayOrder:4,actionType:'external',sourceUrl:'https://www.bitrix24.kz/'},
 {id:'S05',name:'Страхование',provider:'Защита бизнеса',description:'Защита бизнеса от непредвиденных событий.',benefits:[],terms:'',offer:'Страховые решения для имущества и ответственности компании.',imageUrl:'/images/insurance.png',imageAlt:'Объёмный защитный щит над зданием',connectUrl:null,displayOrder:5,actionType:'informational',sourceUrl:null},
 {id:'S06',name:'Бухгалтерия',provider:'Бухта',description:'Бухгалтерские процессы, налоговая отчётность, зарплата и электронные документы.',benefits:['Связанные процессы в одной системе','Автоматизация повседневных операций'],terms:'Состав решения и стоимость уточняются у поставщика.',offer:'Порядок в учёте. Время для развития.',imageUrl:'/images/accounting.png',imageAlt:'Объёмный калькулятор и учётные документы',connectUrl:'https://buhta.com',displayOrder:6,actionType:'external',sourceUrl:'https://buhta.com/'}
];
